# Generated by Django 3.2.12 on 2022-03-26 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Business_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_Analysis_kw_master_kw_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
                ('brand_to_market', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.brandtomarket')),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_kw_magnet_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
                ('brand_to_market', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.brandtomarket')),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_kw_cerebro_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
                ('brand_to_market', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.brandtomarket')),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_kw_ba_output_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
                ('brand_to_market', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.brandtomarket')),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_kw_ba_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
                ('brand_to_market', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.brandtomarket')),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_kw_amz_choice_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
                ('brand_to_market', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.brandtomarket')),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_basic_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
                ('brand_to_market', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.brandtomarket')),
            ],
        ),
    ]
