# Generated by Django 3.2.12 on 2022-03-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_Analysis_basic_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_kw_amz_choice_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_kw_ba_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_kw_ba_output_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_kw_cerebro_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_kw_magnet_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_kw_master_kw_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
