# Generated by Django 4.0.3 on 2022-06-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compet_Analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_Analysis_Data_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_sv', models.BigIntegerField(null=True)),
                ('min_relavency', models.BigIntegerField(null=True)),
                ('max_rank', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_Data_FilterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_phrase', models.PositiveBigIntegerField(null=True)),
                ('search_volume_total', models.PositiveBigIntegerField(null=True)),
                ('top_10_sv', models.CharField(blank=True, max_length=5000, null=True)),
                ('top_10percent_sv', models.CharField(blank=True, max_length=5000, null=True)),
                ('top_30_sv', models.CharField(blank=True, max_length=5000, null=True)),
                ('top_30percent_sv', models.CharField(blank=True, max_length=5000, null=True)),
                ('filter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Compet_Analysis.comp_analysis_data_filter')),
            ],
        ),
        migrations.RenameField(
            model_name='comp_analysis_basic_data',
            old_name='brand_to_market',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='comp_analysis_basic_data',
            old_name='key_word',
            new_name='keyword_auto_validate',
        ),
        migrations.RenameField(
            model_name='comp_analysis_kw_amz_choice_data',
            old_name='key_word',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='comp_analysis_kw_magnet_data',
            old_name='key_word',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='comp_analysis_kw_cerebro_data',
            name='brand_to_market',
        ),
        migrations.RemoveField(
            model_name='comp_analysis_kw_cerebro_data',
            name='key_word',
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='amazon_choice',
            field=models.FileField(blank=True, upload_to='manual_validator/amazon choice'),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='asin1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='asin10',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='asin2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='asin3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='asin4',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='asin5',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='asin6',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='asin7',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='asin8',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='asin9',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='cerebro',
            field=models.FileField(blank=True, upload_to='manual_validator/cerebro'),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='google_trends_ss',
            field=models.FileField(blank=True, upload_to='manual_validator/google trends ss'),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='magnet',
            field=models.FileField(blank=True, upload_to='manual_validator/magnet'),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='xray',
            field=models.FileField(blank=True, upload_to='manual_validator/xray'),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='xray_graph',
            field=models.FileField(blank=True, upload_to='manual_validator/x-ray graphs'),
        ),
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='xray_ss',
            field=models.FileField(blank=True, upload_to='manual_validator/x-ray ss'),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='asin10',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='asin11',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='asin2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='asin3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='asin4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='asin5',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='asin6',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='asin7',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='asin8',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='asin9',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='phrase',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='position',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='search_volume',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='title_density',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comp_analysis_kw_amz_choice_data',
            name='brand_to_market',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Compet_Analysis.comp_analysis_basic_data'),
        ),
        migrations.AlterField(
            model_name='comp_analysis_kw_magnet_data',
            name='brand_to_market',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Compet_Analysis.comp_analysis_basic_data'),
        ),
        migrations.CreateModel(
            name='Comp_Analysis_KW_Cerebro_Data_Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, max_length=1000)),
                ('search_volume', models.CharField(blank=True, max_length=1000)),
                ('title_density', models.CharField(blank=True, max_length=1000, null=True)),
                ('position', models.CharField(blank=True, max_length=1000, null=True)),
                ('asin2', models.CharField(blank=True, max_length=1000)),
                ('asin3', models.CharField(blank=True, max_length=1000)),
                ('asin4', models.CharField(blank=True, max_length=1000)),
                ('asin5', models.CharField(blank=True, max_length=1000)),
                ('asin6', models.CharField(blank=True, max_length=1000)),
                ('asin7', models.CharField(blank=True, max_length=1000)),
                ('asin8', models.CharField(blank=True, max_length=1000)),
                ('asin9', models.CharField(blank=True, max_length=1000)),
                ('asin10', models.CharField(blank=True, max_length=1000)),
                ('asin11', models.CharField(blank=True, max_length=1000)),
                ('keyword', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Compet_Analysis.comp_analysis_basic_data')),
            ],
        ),
        migrations.CreateModel(
            name='Comp_Analysis_Filtered_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, max_length=1000)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('search_volume', models.CharField(blank=True, max_length=1000)),
                ('asin2', models.CharField(blank=True, max_length=1000)),
                ('asin3', models.CharField(blank=True, max_length=1000)),
                ('asin4', models.CharField(blank=True, max_length=1000)),
                ('asin5', models.CharField(blank=True, max_length=1000)),
                ('asin6', models.CharField(blank=True, max_length=1000)),
                ('asin7', models.CharField(blank=True, max_length=1000)),
                ('asin8', models.CharField(blank=True, max_length=1000)),
                ('asin9', models.CharField(blank=True, max_length=1000)),
                ('asin10', models.CharField(blank=True, max_length=1000)),
                ('asin11', models.CharField(blank=True, max_length=1000)),
                ('mv_filtered_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Compet_Analysis.comp_analysis_data_filterresult')),
            ],
        ),
        migrations.AddField(
            model_name='comp_analysis_data_filter',
            name='mv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Compet_Analysis.comp_analysis_basic_data'),
        ),
        migrations.AddField(
            model_name='comp_analysis_kw_cerebro_data',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Compet_Analysis.comp_analysis_kw_cerebro_data_head'),
        ),
    ]
