# Generated by Django 4.0.3 on 2022-06-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compet_Analysis', '0004_comp_analysis_data_filterresult_top_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp_analysis_kw_cerebro_data',
            name='asin11',
        ),
        migrations.RemoveField(
            model_name='comp_analysis_kw_cerebro_data_head',
            name='asin11',
        ),
    ]
