# Generated by Django 4.0.3 on 2022-06-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compet_Analysis', '0006_comp_analysis_kw_cerebro_data_head_excel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_analysis_kw_cerebro_data_head',
            name='excel_file',
            field=models.FileField(blank=True, upload_to='compt_analysis/final_cerebro_excel/'),
        ),
    ]
