# Generated by Django 4.0.3 on 2022-07-07 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compet_Analysis', '0007_alter_comp_analysis_kw_cerebro_data_head_excel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_Analysis_kw_master_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, max_length=1000)),
                ('search_volume', models.CharField(blank=True, max_length=1000)),
                ('title_density', models.CharField(blank=True, max_length=1000)),
                ('source', models.CharField(blank=True, max_length=1000)),
                ('relevancy', models.CharField(blank=True, max_length=1000)),
                ('filtered_comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Compet_Analysis.comp_analysis_data_filterresult')),
            ],
        ),
        migrations.RemoveField(
            model_name='comp_analysis_kw_ba_data',
            name='brand_to_market',
        ),
        migrations.RemoveField(
            model_name='comp_analysis_kw_ba_output_data',
            name='brand_to_market',
        ),
        migrations.RemoveField(
            model_name='comp_analysis_kw_magnet_data',
            name='brand_to_market',
        ),
        migrations.RemoveField(
            model_name='comp_analysis_kw_master_kw_data',
            name='brand_to_market',
        ),
        migrations.DeleteModel(
            name='Comp_Analysis_kw_amz_choice_data',
        ),
        migrations.DeleteModel(
            name='Comp_Analysis_kw_ba_data',
        ),
        migrations.DeleteModel(
            name='Comp_Analysis_kw_ba_output_data',
        ),
        migrations.DeleteModel(
            name='Comp_Analysis_kw_magnet_data',
        ),
        migrations.DeleteModel(
            name='Comp_Analysis_kw_master_kw_data',
        ),
    ]
