# Generated by Django 4.0.3 on 2022-07-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compet_Analysis', '0009_comp_analysis_data_filterresult_filtered_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_analysis_data_filterresult',
            name='filtered_file',
            field=models.FileField(blank=True, upload_to='compt_analysis/filtered_cerebro_excel/'),
        ),
    ]
