# Generated by Django 4.0.3 on 2022-07-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compet_Analysis', '0010_alter_comp_analysis_data_filterresult_filtered_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_analysis_kw_master_table',
            name='filtered_comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Compet_Analysis.comp_analysis_basic_data'),
        ),
    ]
