# Generated by Django 4.0.3 on 2022-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compet_Analysis', '0011_alter_comp_analysis_kw_master_table_filtered_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_analysis_basic_data',
            name='master_table',
            field=models.BooleanField(default=False),
        ),
    ]
