# Generated by Django 3.2.12 on 2022-02-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street1', models.CharField(max_length=200)),
                ('street2', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('registered_address', models.BooleanField(max_length=200)),
                ('trading_address', models.BooleanField(max_length=200)),
                ('directors_address', models.BooleanField(max_length=200)),
            ],
        ),
    ]
