# Generated by Django 3.2.12 on 2022-03-03 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiontostaff',
            name='brand_to_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.brandtomarket'),
        ),
    ]
