# Generated by Django 3.2.12 on 2022-03-03 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Business_Admin', '0002_permissiontostaff_brand_to_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiontostaff',
            name='staff_permission',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
        migrations.RemoveField(
            model_name='permissiontostaff',
            name='to_staff',
        ),
        migrations.AddField(
            model_name='permissiontostaff',
            name='to_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
