# Generated by Django 3.2.12 on 2022-02-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Admin', '0002_auto_20220222_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='directors_address',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='registered_address',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='trading_address',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='auth_code',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='registration_number',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trade_mark', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.brands')),
            ],
        ),
        migrations.AddField(
            model_name='brands',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.companymodel'),
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('sort_code', models.BigIntegerField(null=True)),
                ('account_number', models.BigIntegerField(null=True)),
                ('iban', models.CharField(max_length=20)),
                ('swift_code', models.CharField(max_length=20)),
                ('street1', models.CharField(max_length=200)),
                ('street2', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.companymodel')),
            ],
        ),
    ]
