# Generated by Django 3.2.12 on 2022-02-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Admin', '0003_auto_20220222_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='auth_code',
            field=models.BigIntegerField(blank=True, help_text='Enter Authentication Code'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='certi_incorp',
            field=models.FileField(blank=True, help_text='Upload a copy of certificate incorpation', upload_to='incorp_certificates'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='directors_name1',
            field=models.CharField(blank=True, help_text='Enter Directore Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='directors_name2',
            field=models.CharField(blank=True, help_text='Enter Director name 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='name',
            field=models.CharField(blank=True, help_text='Enter Company Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='registration_number',
            field=models.BigIntegerField(blank=True, help_text='Enter company registration number'),
        ),
    ]
