# Generated by Django 4.0.3 on 2022-04-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Admin', '0003_alter_brandtomarket_trade_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiontostaff',
            name='staff_modules',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.CreateModel(
            name='PendingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_staff', models.EmailField(blank=True, max_length=254, null=True)),
                ('brand_to_country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.brandtomarket')),
            ],
        ),
    ]
