# Generated by Django 3.2.12 on 2022-03-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Admin', '0003_auto_20220303_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='director1_address',
            field=models.ForeignKey(blank=True, help_text='Select Director 1 Address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_address', to='Business_Admin.address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='director2_address',
            field=models.ForeignKey(blank=True, help_text='Select Director 2 Address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_address2', to='Business_Admin.address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_address',
            field=models.ForeignKey(blank=True, help_text='Select Registration Address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_address', to='Business_Admin.address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='trading_address',
            field=models.ForeignKey(blank=True, help_text='Select Trading Address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_address', to='Business_Admin.address'),
        ),
    ]
