# Generated by Django 4.0.3 on 2022-04-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Admin', '0004_permissiontostaff_staff_modules_pendingstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingstaff',
            name='brand_to_country',
        ),
    ]
