# Generated by Django 3.2.12 on 2022-02-24 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Admin', '0005_auto_20220224_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='area',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='state',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='street2',
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='bank_address',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='bank_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_address', to='Business_Admin.addressmodel'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='directors_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_address2', to='Business_Admin.addressmodel'),
        ),
    ]
