# Generated by Django 3.2.12 on 2022-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Admin', '0006_auto_20220224_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='bank_address',
            new_name='banks_address',
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='my_bank_address',
            field=models.BooleanField(blank=True, default=False, help_text='Select as Bank address'),
        ),
    ]
