# Generated by Django 3.2.12 on 2022-02-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Admin', '0007_auto_20220224_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markets',
            name='brand',
        ),
    ]
