# Generated by Django 3.2.12 on 2022-02-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Admin', '0009_auto_20220224_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='market',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='trade_mark',
        ),
        migrations.CreateModel(
            name='TradeMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_mark', models.CharField(blank=True, max_length=200)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.brands')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.markets')),
            ],
        ),
    ]
