# Generated by Django 4.0.3 on 2022-04-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Business_Admin', '0005_remove_pendingstaff_brand_to_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Business_Admin.brandtomarket')),
            ],
        ),
        migrations.CreateModel(
            name='ManualValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin1', models.CharField(blank=True, max_length=30)),
                ('asin2', models.CharField(blank=True, max_length=30)),
                ('asin3', models.CharField(blank=True, max_length=30)),
                ('asin4', models.CharField(blank=True, max_length=30)),
                ('asin5', models.CharField(blank=True, max_length=30)),
                ('asin6', models.CharField(blank=True, max_length=30)),
                ('asin7', models.CharField(blank=True, max_length=30)),
                ('asin8', models.CharField(blank=True, max_length=30)),
                ('asin9', models.CharField(blank=True, max_length=30)),
                ('asin10', models.CharField(blank=True, max_length=30)),
                ('xray_graph', models.FileField(upload_to='media/x-ray graphs')),
                ('xray_ss', models.FileField(upload_to='media/x-ray ss')),
                ('google_trends_ss', models.FileField(upload_to='media/google trends ss')),
                ('xray', models.FileField(upload_to='media/xray')),
                ('cerebro', models.FileField(upload_to='media/cerebro')),
                ('amazon_choice', models.FileField(upload_to='media/amazon choice')),
                ('magnet', models.FileField(upload_to='media/magnet')),
                ('keyword', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Prod_Validator.keyword')),
            ],
        ),
    ]
