# Generated by Django 4.0.3 on 2022-04-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod_Validator', '0002_remove_manualvalidator_keyword_manualvalidator_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualValidatorHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, max_length=1000)),
                ('search_volume', models.CharField(blank=True, max_length=1000)),
                ('title_density', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('asin2', models.CharField(blank=True, max_length=1000)),
                ('asin3', models.CharField(blank=True, max_length=1000)),
                ('asin4', models.CharField(blank=True, max_length=1000)),
                ('asin5', models.CharField(blank=True, max_length=1000)),
                ('asin6', models.CharField(blank=True, max_length=1000)),
                ('asin7', models.CharField(blank=True, max_length=1000)),
                ('asin8', models.CharField(blank=True, max_length=1000)),
                ('asin9', models.CharField(blank=True, max_length=1000)),
                ('asin10', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
