# Generated by Django 4.0.3 on 2022-04-26 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prod_Validator', '0003_manualvalidatorhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualvalidatorhead',
            name='asin11',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='manualvalidatorhead',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prod_Validator.manualvalidator'),
        ),
        migrations.CreateModel(
            name='ManualValidatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prod_Validator.manualvalidatorhead')),
            ],
        ),
    ]
