# Generated by Django 4.0.3 on 2022-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod_Validator', '0005_manualvalidatordata_asin10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualvalidator',
            name='amazon_choice',
            field=models.FileField(blank=True, upload_to='manual_validator/amazon choice'),
        ),
        migrations.AlterField(
            model_name='manualvalidator',
            name='cerebro',
            field=models.FileField(blank=True, upload_to='manual_validator/cerebro'),
        ),
        migrations.AlterField(
            model_name='manualvalidator',
            name='google_trends_ss',
            field=models.FileField(blank=True, upload_to='manual_validator/google trends ss'),
        ),
        migrations.AlterField(
            model_name='manualvalidator',
            name='magnet',
            field=models.FileField(blank=True, upload_to='manual_validator/magnet'),
        ),
        migrations.AlterField(
            model_name='manualvalidator',
            name='xray',
            field=models.FileField(blank=True, upload_to='manual_validator/xray'),
        ),
        migrations.AlterField(
            model_name='manualvalidator',
            name='xray_graph',
            field=models.FileField(blank=True, upload_to='manual_validator/x-ray graphs'),
        ),
        migrations.AlterField(
            model_name='manualvalidator',
            name='xray_ss',
            field=models.FileField(blank=True, upload_to='manual_validator/x-ray ss'),
        ),
    ]
