# Generated by Django 4.0.3 on 2022-04-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod_Validator', '0006_alter_manualvalidator_amazon_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualvalidatorhead',
            name='position',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='manualvalidatorhead',
            name='title_density',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
