# Generated by Django 4.0.3 on 2022-05-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prod_Validator', '0008_alter_manualvalidatorhead_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualValidatorDataFilterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_volume_total', models.PositiveBigIntegerField(null=True)),
                ('top_10_sv', models.CharField(blank=True, max_length=5000, null=True)),
                ('top_10percent_sv', models.CharField(blank=True, max_length=5000, null=True)),
                ('top_30_sv', models.CharField(blank=True, max_length=5000, null=True)),
                ('top_30percent_sv', models.CharField(blank=True, max_length=5000, null=True)),
                ('filter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prod_Validator.manualvalidatorhead')),
            ],
        ),
        migrations.CreateModel(
            name='ManualValidatorDataFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_sv', models.BigIntegerField(null=True)),
                ('min_relavency', models.BigIntegerField(null=True)),
                ('max_rank', models.BigIntegerField(null=True)),
                ('head', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prod_Validator.manualvalidatorhead')),
            ],
        ),
    ]
