# Generated by Django 4.0.3 on 2022-05-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prod_Validator', '0009_manualvalidatordatafilterresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualvalidatordatafilterresult',
            name='filter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prod_Validator.manualvalidatordatafilter'),
        ),
    ]
