# Generated by Django 4.0.3 on 2022-05-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prod_Validator', '0010_alter_manualvalidatordatafilterresult_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualvalidatordatafilter',
            name='head',
        ),
        migrations.AddField(
            model_name='manualvalidatordatafilter',
            name='mv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prod_Validator.manualvalidator'),
        ),
        migrations.CreateModel(
            name='ManualValidatorFilteredData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, max_length=1000)),
                ('search_volume', models.CharField(blank=True, max_length=1000)),
                ('asin2', models.CharField(blank=True, max_length=1000)),
                ('asin3', models.CharField(blank=True, max_length=1000)),
                ('asin4', models.CharField(blank=True, max_length=1000)),
                ('asin5', models.CharField(blank=True, max_length=1000)),
                ('asin6', models.CharField(blank=True, max_length=1000)),
                ('asin7', models.CharField(blank=True, max_length=1000)),
                ('asin8', models.CharField(blank=True, max_length=1000)),
                ('asin9', models.CharField(blank=True, max_length=1000)),
                ('asin10', models.CharField(blank=True, max_length=1000)),
                ('asin11', models.CharField(blank=True, max_length=1000)),
                ('m_validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prod_Validator.manualvalidator')),
            ],
        ),
    ]
