# Generated by Django 4.0.3 on 2022-05-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prod_Validator', '0011_remove_manualvalidatordatafilter_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualvalidatorfiltereddata',
            name='m_validator',
        ),
        migrations.AddField(
            model_name='manualvalidatorfiltereddata',
            name='mv_filtered_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prod_Validator.manualvalidatordatafilterresult'),
        ),
    ]
