# Generated by Django 4.0.3 on 2022-06-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod_Validator', '0012_remove_manualvalidatorfiltereddata_m_validator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualvalidatorfiltereddata',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
