# Generated by Django 4.0.3 on 2022-06-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod_Validator', '0013_manualvalidatorfiltereddata_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualvalidatordatafilterresult',
            name='total_phrase',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
