# Generated by Django 3.2.12 on 2022-02-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(help_text='Enter Name', max_length=100),
        ),
    ]
