# Generated by Django 3.2.12 on 2022-02-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plans', '0002_alter_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='brands_limit',
            field=models.IntegerField(help_text='Enter Brand Limit'),
        ),
        migrations.AlterField(
            model_name='package',
            name='comp_analysis_limit',
            field=models.IntegerField(help_text='Enter Company Analysis limit'),
        ),
        migrations.AlterField(
            model_name='package',
            name='company_limit',
            field=models.IntegerField(help_text='Enter Company Limit'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(help_text='Enter Description', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='listings_limit',
            field=models.IntegerField(help_text='Enter Listing Limit'),
        ),
        migrations.AlterField(
            model_name='package',
            name='markets_limit',
            field=models.IntegerField(help_text='Enter Markets Limit'),
        ),
        migrations.AlterField(
            model_name='package',
            name='ppc_generation_limit',
            field=models.IntegerField(help_text='Enter PPC Generation Limit'),
        ),
        migrations.AlterField(
            model_name='package',
            name='ppc_optimization_limit',
            field=models.IntegerField(help_text='Enter PPC Optimization Limit'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pricing_per_month',
            field=models.IntegerField(help_text='Enter Price for per month'),
        ),
        migrations.AlterField(
            model_name='package',
            name='product_validation_limit',
            field=models.IntegerField(help_text='Enter Product Validation Limit'),
        ),
        migrations.AlterField(
            model_name='package',
            name='users_limit',
            field=models.IntegerField(help_text='Enter Users Limit'),
        ),
    ]
